const SCHEMA_RANGES = [
  { name: "Emotional Deprivation", start: 1, end: 9 },
  { name: "Abandonment / Instability", start: 10, end: 26 },
  { name: "Mistrust / Abuse", start: 27, end: 43 },
  { name: "Social Isolation / Alienation", start: 44, end: 53 },
  { name: "Defectiveness / Shame", start: 54, end: 68 },
  { name: "Failure", start: 69, end: 77},
  { name: "Dependence / Incompetence", start: 78, end: 92 },
  { name: "Vulnerability to Harm", start:93, end: 104 },
  { name: "Enmeshment", start:105, end: 115 },
  { name: "Subjugation", start: 116, end: 125 },
  { name: "Self-Sacrifice", start: 126, end:142 },
  { name: "Emotional Inhibition", start: 143, end: 151 },
  { name: "Unrelenting Standards", start: 152, end: 168 },
  { name: "Entitlement", start: 169, end: 178 },
  { name: "Insufficient Self-Control", start: 179, end: 193},
  { name: "Approval Seeking", start:194, end: 207 },
  { name: "Negativity / Pessimism", start: 208, end: 218},
  { name: "Punitiveness", start: 219, end: 232}
];


const QUESTIONS =[
  { id: 1, text: "There has never been anyone in my life who truly understood and responded to my emotional needs." },
  { id: 2, text: "I did not receive enough love and attention." },
  { id: 3, text: "For the most part, I have not had anyone to guide me or provide emotional support." },
  { id: 4, text: "For the most part, I have not had anyone who really cared about me or was genuinely interested in what was happening in my inner world." },
  { id: 5, text: "For most of my life, I have not had anyone who really listened to me." },
  { id: 6, text: "For the most part, I have not had anyone who gave me warmth, holding, and affection." },
  { id: 7, text: "I have rarely felt that I was special to someone." },
  { id: 8, text: "For most of my life, I have not had anyone who truly loved me." },
  { id: 9, text: "Very rarely in my life has there been someone who could truly understand me." },

  { id: 10, text: "I worry that people I feel close to will leave me." },
  { id: 11, text: "I tend to become clingy in my close relationships." },
  { id: 12, text: "I worry that the people I love will abandon me." },
  { id: 13, text: "I feel that I lack stable sources of emotional support." },
  { id: 14, text: "I do not believe that important relationships will last." },
  { id: 15, text: "I feel overly dependent on people I am close to." },
  { id: 16, text: "I believe that in the end I will end up alone." },
  { id: 17, text: "When I sense someone pulling away, I panic." },
  { id: 18, text: "My fear that people will leave me sometimes feels overwhelming." },
  { id: 19, text: "I get very upset when someone leaves me alone." },
  { id: 20, text: "I cannot rely on people unless they are physically close to me." },
  { id: 21, text: "I often worry that others will not stay emotionally available to me." },
  { id: 22, text: "I fear that people I depend on will disappear from my life." },
  { id: 23, text: "I feel anxious when I am not sure where I stand with someone important to me." },
  { id: 24, text: "I worry that people will eventually lose interest in me." },
  { id: 25, text: "I become distressed when someone I care about is unavailable." },
  { id: 26, text: "I feel insecure in close relationships." },

  { id: 27, text: "I feel that people will take advantage of me." },
  { id: 28, text: "I am usually on guard with others." },
  { id: 29, text: "I expect that people will intentionally hurt me." },
  { id: 30, text: "I find it difficult to trust people completely." },
  { id: 31, text: "I worry that others will manipulate me." },
  { id: 32, text: "I feel that people will betray me if given the chance." },
  { id: 33, text: "I am suspicious of other people's motives." },
  { id: 34, text: "I often assume that others have hidden agendas." },
  { id: 35, text: "I believe that most people cannot be trusted." },
  { id: 36, text: "I am wary of letting people get too close to me." },
  { id: 37, text: "I expect that people will lie to me." },
  { id: 38, text: "I feel that others will try to use me for their own purposes." },
  { id: 39, text: "I am alert to signs that someone might hurt me." },
  { id: 40, text: "I rarely feel safe being emotionally open with others." },
  { id: 41, text: "I expect that people will eventually disappoint me." },
  { id: 42, text: "I feel that people are generally not trustworthy." },
  { id: 43, text: "I often question other people's true intentions." },

  { id: 44, text: "I feel different from other people." },
  { id: 45, text: "I do not really feel that I belong anywhere." },
  { id: 46, text: "I feel isolated from other people." },
  { id: 47, text: "I often feel like an outsider." },
  { id: 48, text: "I feel disconnected from groups." },
  { id: 49, text: "I rarely feel part of a community." },
  { id: 50, text: "I feel socially excluded." },
  { id: 51, text: "I feel that I do not fit in with others." },
  { id: 52, text: "I feel fundamentally different from most people." },
  { id: 53, text: "I often feel alone even when I am with people." },

  { id: 54, text: "I feel that I am flawed and defective." },
  { id: 55, text: "I feel unworthy of love." },
  { id: 56, text: "I feel that if people really knew me, they would reject me." },
  { id: 57, text: "I feel ashamed of who I am." },
  { id: 58, text: "I feel fundamentally inadequate." },
  { id: 59, text: "I believe there is something wrong with me." },
  { id: 60, text: "I feel deeply insecure about myself." },
    { id: 61, text: "I feel that others would see me as unlovable if they truly knew me." },
  { id: 62, text: "I feel inferior to most people." },
  { id: 63, text: "I feel unattractive or undesirable." },
  { id: 64, text: "I often feel exposed and vulnerable to criticism." },
  { id: 65, text: "I feel that I do not measure up to others." },
  { id: 66, text: "I worry that people will discover my shortcomings." },
  { id: 67, text: "I feel deeply self-conscious around others." },
  { id: 68, text: "I feel defective compared to other people." },

  { id: 69, text: "I feel that I have failed compared to my peers." },
  { id: 70, text: "I believe I am less capable than most people." },
  { id: 71, text: "I feel that I will inevitably fail in important areas of life." },
  { id: 72, text: "I feel incompetent in many areas." },
  { id: 73, text: "I feel that I am not as talented as others." },
  { id: 74, text: "I believe I am destined to fail." },
  { id: 75, text: "I feel that others are more successful than I am." },
  { id: 76, text: "I often feel inadequate in my achievements." },
  { id: 77, text: "I feel that I cannot perform as well as others." },

  { id: 78, text: "I feel unable to handle everyday responsibilities without help." },
  { id: 79, text: "I feel dependent on others to function effectively." },
  { id: 80, text: "I feel incapable of making good decisions on my own." },
  { id: 81, text: "I lack confidence in my ability to solve problems independently." },
  { id: 82, text: "I feel helpless when I have to take care of things by myself." },
  { id: 83, text: "I rely too much on others for guidance." },
  { id: 84, text: "I feel overwhelmed when I must act independently." },
  { id: 85, text: "I doubt my ability to manage daily life alone." },
  { id: 86, text: "I feel incapable of coping without support." },
  { id: 87, text: "I feel unsure of myself when making important decisions." },
  { id: 88, text: "I feel that I need others to tell me what to do." },
  { id: 89, text: "I feel weak when I am on my own." },
  { id: 90, text: "I feel that I cannot function independently for long." },
  { id: 91, text: "I feel insecure about handling responsibilities alone." },
  { id: 92, text: "I feel unable to manage life without significant help." },

  { id: 93, text: "I worry that a catastrophe could strike at any moment." },
  { id: 94, text: "I often feel that something terrible is about to happen." },
  { id: 95, text: "I am overly worried about my health." },
  { id: 96, text: "I worry excessively about accidents or disasters." },
  { id: 97, text: "I feel vulnerable to serious illness." },
  { id: 98, text: "I fear that I might suddenly lose everything." },
  { id: 99, text: "I am preoccupied with thoughts of danger." },
  { id: 100, text: "I often imagine worst-case scenarios." },
  { id: 101, text: "I feel that the world is a dangerous place." },
  { id: 102, text: "I worry that I will not be able to handle emergencies." },
  { id: 103, text: "I feel constantly on edge about potential threats." },
  { id: 104, text: "I fear that disaster could happen at any time." },

  { id: 105, text: "I feel overly emotionally involved with someone close to me." },
  { id: 106, text: "I have difficulty knowing where I end and another person begins." },
  { id: 107, text: "My sense of identity feels tied to someone else." },
  { id: 108, text: "I feel incomplete without a particular person in my life." },
  { id: 109, text: "I have trouble functioning independently from someone close." },
  { id: 110, text: "I feel overly responsible for another person's feelings." },
  { id: 111, text: "I feel guilty when I try to separate from someone close to me." },
  { id: 112, text: "I often sacrifice my independence to stay emotionally connected." },
  { id: 113, text: "I feel that my personal identity is not fully developed." },
  { id: 114, text: "I struggle to make decisions without considering a specific person." },
  { id: 115, text: "I feel anxious when I am emotionally separate from someone close." },

  { id: 116, text: "I tend to give in to others to avoid conflict." },
  { id: 117, text: "I let others control situations to keep the peace." },
  { id: 118, text: "I feel that my needs are less important than others' needs." },
  { id: 119, text: "I often suppress my preferences to avoid upsetting people." },
  { id: 120, text: "I feel uncomfortable asserting myself." },
    { id: 121, text: "I worry that expressing my needs will lead to rejection or conflict." },
  { id: 122, text: "I usually put other people's wishes ahead of my own." },
  { id: 123, text: "I find it hard to stand up for myself." },
  { id: 124, text: "I often feel pressured to meet others' expectations." },
  { id: 125, text: "I avoid confrontation even when I am treated unfairly." },

  { id: 126, text: "I am the one who usually ends up taking care of others." },
  { id: 127, text: "I feel responsible for other people's well-being." },
  { id: 128, text: "I often neglect my own needs to help others." },
  { id: 129, text: "I feel guilty when I put my own needs first." },
  { id: 130, text: "I tend to give more to others than I receive." },
  { id: 131, text: "I am overly focused on meeting other people's needs." },
  { id: 132, text: "I often sacrifice my own comfort for others." },
  { id: 133, text: "I feel selfish when I prioritize myself." },
  { id: 134, text: "I feel compelled to help others even when it costs me." },
  { id: 135, text: "I often feel drained from taking care of others." },
  { id: 136, text: "I put others first even when I am overwhelmed." },
  { id: 137, text: "I feel uneasy when I am not helping someone." },
  { id: 138, text: "I often ignore my own feelings to support others." },
  { id: 139, text: "I feel responsible for fixing other people's problems." },
  { id: 140, text: "I struggle to set limits with people who need me." },
  { id: 141, text: "I feel compelled to be the strong one for others." },
  { id: 142, text: "I often give more emotional support than I receive." },

  { id: 143, text: "I keep my emotions tightly controlled." },
  { id: 144, text: "I find it difficult to express my feelings openly." },
  { id: 145, text: "I hold back my emotions even when I want to express them." },
  { id: 146, text: "I worry that showing emotions will lead to disapproval." },
  { id: 147, text: "I tend to appear emotionally reserved." },
  { id: 148, text: "I feel uncomfortable when others show strong emotions." },
  { id: 149, text: "I try to stay rational and avoid emotional displays." },
  { id: 150, text: "I suppress emotional reactions." },
  { id: 151, text: "I rarely let my guard down emotionally." },

  { id: 152, text: "I feel that I must meet very high standards." },
  { id: 153, text: "I push myself hard to avoid making mistakes." },
  { id: 154, text: "I am very self-critical when I fall short." },
  { id: 155, text: "I feel pressure to perform perfectly." },
  { id: 156, text: "I set extremely high expectations for myself." },
  { id: 157, text: "I feel that what I do is rarely good enough." },
  { id: 158, text: "I am driven to achieve more and more." },
  { id: 159, text: "I have difficulty relaxing because of my standards." },
  { id: 160, text: "I feel constant pressure to improve myself." },
  { id: 161, text: "I focus heavily on productivity and achievement." },
  { id: 162, text: "I feel uneasy when I am not being productive." },
  { id: 163, text: "I judge myself harshly for mistakes." },
  { id: 164, text: "I feel that I must always be efficient." },
  { id: 165, text: "I struggle to accept average performance." },
  { id: 166, text: "I feel driven to meet very demanding goals." },
  { id: 167, text: "I have trouble slowing down." },
  { id: 168, text: "I feel that I should always be doing more." },

  { id: 169, text: "I feel that I am entitled to special treatment." },
  { id: 170, text: "I have difficulty accepting limits placed on me." },
  { id: 171, text: "I dislike being told what to do." },
  { id: 172, text: "I feel frustrated when I cannot do things the way I want." },
  { id: 173, text: "I feel that rules should not apply to me in the same way." },
  { id: 174, text: "I get impatient when my wishes are not met immediately." },
  { id: 175, text: "I feel that I deserve more than others." },
  { id: 176, text: "I have trouble compromising." },
  { id: 177, text: "I feel irritated when others set boundaries with me." },
  { id: 178, text: "I expect a lot from the people around me." },

  { id: 179, text: "I have difficulty controlling my impulses." },
  { id: 180, text: "I struggle to tolerate frustration." },
    { id: 181, text: "I act on my feelings without thinking things through." },
  { id: 182, text: "I find it hard to delay gratification." },
  { id: 183, text: "I have trouble disciplining myself." },
  { id: 184, text: "I often give in to temptation." },
  { id: 185, text: "I have difficulty following through on boring or routine tasks." },
  { id: 186, text: "I avoid tasks that require sustained effort." },
  { id: 187, text: "I get frustrated easily when things are difficult." },
  { id: 188, text: "I struggle to stick with long-term goals." },
  { id: 189, text: "I tend to quit when tasks become uncomfortable." },
  { id: 190, text: "I find it hard to persist when things are not immediately rewarding." },
  { id: 191, text: "I have difficulty controlling my emotions when upset." },
  { id: 192, text: "I tend to react impulsively under stress." },
  { id: 193, text: "I struggle to maintain self-discipline." },

  { id: 194, text: "It is very important to me that others approve of me." },
  { id: 195, text: "I worry a lot about what others think of me." },
  { id: 196, text: "I try hard to gain recognition from others." },
  { id: 197, text: "My self-esteem depends heavily on others' opinions." },
  { id: 198, text: "I feel driven to impress people." },
  { id: 199, text: "I am very sensitive to criticism." },
  { id: 200, text: "I worry about losing social status." },
  { id: 201, text: "I feel uncomfortable when I am not liked." },
  { id: 202, text: "I often change my behavior to gain approval." },
  { id: 203, text: "I place great importance on how I appear to others." },
  { id: 204, text: "I feel anxious when I think others disapprove of me." },
  { id: 205, text: "I am highly motivated by praise and recognition." },
  { id: 206, text: "I feel upset when I am not appreciated." },
  { id: 207, text: "I care deeply about maintaining a positive image." },

  { id: 208, text: "I tend to focus on the negative side of things." },
  { id: 209, text: "I expect that things will go wrong." },
  { id: 210, text: "I often worry about worst-case scenarios." },
  { id: 211, text: "I find it hard to stay optimistic." },
  { id: 212, text: "I dwell on potential problems." },
  { id: 213, text: "I am more aware of risks than opportunities." },
  { id: 214, text: "I tend to anticipate disappointment." },
  { id: 215, text: "I focus more on what could go wrong than right." },
  { id: 216, text: "I often feel that the future looks bleak." },
  { id: 217, text: "I worry excessively about possible mistakes." },
  { id: 218, text: "I have difficulty letting go of negative thoughts." },

  { id: 219, text: "I believe people should be punished for their mistakes." },
  { id: 220, text: "I am intolerant of people who make repeated errors." },
  { id: 221, text: "I tend to be harsh when judging mistakes." },
  { id: 222, text: "I have little patience for human weakness." },
  { id: 223, text: "I believe consequences should be strict when rules are broken." },
  { id: 224, text: "I feel that mistakes deserve strong criticism." },
  { id: 225, text: "I am hard on myself when I mess up." },
  { id: 226, text: "I believe people should pay for their wrongdoing." },
  { id: 227, text: "I struggle to forgive mistakes — my own or others'." },
  { id: 228, text: "I feel that being lenient encourages irresponsibility." },
  { id: 229, text: "I tend to hold grudges after someone makes a serious mistake." },
  { id: 230, text: "I believe discipline should be strict." },
  { id: 231, text: "I find it hard to accept excuses for poor behavior." },
  { id: 232, text: "I believe consequences should be severe when people act wrongly." }
];

